# paths
project_dir: /path/to/project
fastq_dir: /path/to/fastq
output_dir: /path/to/output
sample_table: samples.tsv   # see below sample format

# genome/index files
rrna_index: /path/to/bowtie2_rrna_index
star_genome_dir: /path/to/STAR_genome_index
gtf: /path/to/annotation.gtf

# general params
threads: 8
adapter_seq: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

# featureCounts params
annotation_gtf: /path/to/annotation.gtf
featureCounts_threads: 8

# Ribo parameters
ribo_read_min: 25
ribo_read_max: 35
